# team-vpn — GCP OpenVPN endpoint in us-west1-a
# split-tunnel · UDP/1194 · client CIDR 10.100.0.0/22
# Generated by DeepAgent. Regenerating overwrites this file.

data "google_compute_network" "this" {
  name = "myfirstvpc"
}

data "google_compute_subnetwork" "this" {
  name   = "public-subent"
  region = "us-west1"
}

data "google_compute_image" "boot" {
  family  = "ubuntu-2204-lts"
  project = "ubuntu-os-cloud"
}

# ── Auto-generated PKI (CA + server + initial client cert) ──
# Same resource layout as the AWS Client VPN generator so the shared
# resolveCaFromState helper works for both providers. The CA private key is
# a SENSITIVE output on purpose — the app's issue-user endpoint uses it to
# mint additional per-user certs off this CA without re-running Terraform.

resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem = tls_private_key.ca.private_key_pem

  subject {
    common_name  = "vasanth-ca"
    organization = "DeepAgent GCP OpenVPN"
  }

  is_ca_certificate     = true
  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "digital_signature",
  ]
}

resource "tls_private_key" "server" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "server" {
  private_key_pem = tls_private_key.server.private_key_pem

  dns_names = ["vasanth-server.deepagent.local"]

  subject {
    common_name  = "vasanth-server.deepagent.local"
    organization = "DeepAgent GCP OpenVPN"
  }
}

resource "tls_locally_signed_cert" "server" {
  cert_request_pem   = tls_cert_request.server.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760 # 1 year — rotate before this expires

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "tls_private_key" "client" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "client" {
  private_key_pem = tls_private_key.client.private_key_pem

  subject {
    common_name  = "vasanth-client"
    organization = "DeepAgent GCP OpenVPN"
  }
}

resource "tls_locally_signed_cert" "client" {
  cert_request_pem   = tls_cert_request.client.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "client_auth",
  ]
}

# Diffie-Hellman parameters for OpenVPN. Terraform can't generate real DH
# params, so the startup script does it on first boot (openssl dhparam).

resource "google_compute_address" "vpn" {
  name         = "team-vpn-openvpn-ip"
  region       = "us-west1"
  address_type = "EXTERNAL"
  description  = "Static public IP for the team-vpn OpenVPN endpoint"
}

# ── Firewall: allow client OpenVPN traffic to the VM ──
resource "google_compute_firewall" "vpn_ingress" {
  name    = "team-vpn-openvpn-ingress"
  network = data.google_compute_network.this.self_link

  allow {
    protocol = "udp"
    ports    = ["1194"]
  }

  # Cert auth happens at the OpenVPN layer regardless of source_ranges; this
  # is the outer defensive layer. Default 0.0.0.0/0 keeps the UX simple —
  # tighten via sourceRanges if you know your team's egress IPs.
  source_ranges = ["0.0.0.0/0"]

  target_tags = ["team-vpn-openvpn"]
}

# ── Firewall: allow IAP-tunnel SSH for ops (35.235.240.0/20 is GCP's IAP range) ──
resource "google_compute_firewall" "vpn_ssh" {
  name    = "team-vpn-openvpn-ssh"
  network = data.google_compute_network.this.self_link

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  source_ranges = ["35.235.240.0/20"]
  target_tags   = ["team-vpn-openvpn"]
}

resource "google_compute_instance" "vpn" {
  name         = "team-vpn-openvpn"
  machine_type = "e2-small"
  zone         = "us-west1-a"
  tags         = ["team-vpn-openvpn"]

  boot_disk {
    initialize_params {
      image = data.google_compute_image.boot.self_link
      size  = 15
      type  = "pd-balanced"
    }
  }

  network_interface {
    network    = data.google_compute_network.this.self_link
    subnetwork = data.google_compute_subnetwork.this.self_link
    access_config {
      # Bind the static IP so clients have a stable endpoint address.
      nat_ip = google_compute_address.vpn.address
    }
  }

  # ── IP-forwarding at the GCE layer ──
  # Without this, the hypervisor drops packets whose source IP isn't the
  # instance's own — breaks the NAT'd tunnel traffic. Required for any
  # NAT/router VM in GCP.
  can_ip_forward = true

  # Pass the PEMs into the VM as instance metadata. The startup script pulls
  # them from the metadata service on first boot. Startup script itself is
  # also delivered via metadata (metadata_startup_script is a convenience).
  metadata = {
    "ca-cert-pem"     = tls_self_signed_cert.ca.cert_pem
    "server-cert-pem" = tls_locally_signed_cert.server.cert_pem
    "server-key-pem"  = tls_private_key.server.private_key_pem
  }

  metadata_startup_script = <<-EOT
    #!/bin/bash
    set -euo pipefail
    exec > /var/log/deepagent-openvpn-startup.log 2>&1
    echo "[deepagent] OpenVPN startup: $(date -u)"
    
    if [[ -f /etc/openvpn/.provisioned ]]; then
      echo "[deepagent] Already provisioned — skipping."
      exit 0
    fi
    
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y openvpn iptables-persistent openssl curl
    
    # ── Fetch PEMs from instance metadata (Terraform put them there) ──
    MD="http://metadata.google.internal/computeMetadata/v1/instance/attributes"
    H='Metadata-Flavor: Google'
    mkdir -p /etc/openvpn/server /etc/openvpn/ccd
    curl -fsS -H "$H" "$MD/ca-cert-pem"       > /etc/openvpn/server/ca.crt
    curl -fsS -H "$H" "$MD/server-cert-pem"   > /etc/openvpn/server/server.crt
    curl -fsS -H "$H" "$MD/server-key-pem"    > /etc/openvpn/server/server.key
    chmod 600 /etc/openvpn/server/server.key
    
    # ── DH params (2048-bit; ~30s on e2-small) ──
    openssl dhparam -out /etc/openvpn/server/dh.pem 2048
    
    # ── Server config ──
    cat > /etc/openvpn/server/server.conf <<'OVPNEOF'
    port 1194
    proto udp
    dev tun
    ca   /etc/openvpn/server/ca.crt
    cert /etc/openvpn/server/server.crt
    key  /etc/openvpn/server/server.key
    dh   /etc/openvpn/server/dh.pem
    topology subnet
    server 10.100.0.0 255.255.252.0
    ifconfig-pool-persist /var/log/openvpn/ipp.txt
    # Split-tunnel: only advertise the VPC route to clients.
    push "route 10.0.1.0 255.255.255.0"
    keepalive 10 60
    cipher AES-256-GCM
    data-ciphers AES-256-GCM:AES-128-GCM
    auth SHA256
    persist-key
    persist-tun
    user  nobody
    group nogroup
    verb 3
    status /var/log/openvpn/status.log
    log-append /var/log/openvpn/openvpn.log
    OVPNEOF
    mkdir -p /var/log/openvpn
    
    # ── IP forwarding + iptables NAT (needed even for split-tunnel so return
    #    traffic from the VPC reaches the client via the tun interface) ──
    sysctl -w net.ipv4.ip_forward=1
    grep -q "^net.ipv4.ip_forward" /etc/sysctl.conf && \
      sed -i 's/^net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf || \
      echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
    
    # NAT client subnet → outbound interface. GCE VMs have their public IP
    # assigned via SNAT at the hypervisor, so we NAT the tunnel subnet on the
    # instance's primary interface.
    IFACE=$(ip route show default | awk '/default/ {print $5; exit}')
    iptables -t nat -A POSTROUTING -s 10.100.0.0/22 -o "$IFACE" -j MASQUERADE
    iptables -A FORWARD -i tun+ -o "$IFACE" -j ACCEPT
    iptables -A FORWARD -i "$IFACE" -o tun+ -j ACCEPT
    netfilter-persistent save
    
    # ── Enable + start ──
    systemctl enable openvpn-server@server
    systemctl start  openvpn-server@server
    
    touch /etc/openvpn/.provisioned
    echo "[deepagent] OpenVPN startup: DONE $(date -u)"
    
  EOT

  labels = {
    "managed_by" = "deepagent"
    "stack" = "team-vpn"
    "purpose" = "openvpn-endpoint"
    "environment" = "prod"
    "created_by" = "deepagent-gcp-vpn-ui"
  }

  # Force a replace if the PKI changes — otherwise the startup script has
  # already run on the old boot and the new certs won't be picked up.
  lifecycle {
    create_before_destroy = false
  }
}
