server {
    listen 80;
    server_name bookmark.54.234.155.179.sslip.io;
    root /usr/share/nginx/html;
    location / {
        try_files $uri /index.html;
    }
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name techneuralai.54.234.155.179.sslip.io;
    root /usr/share/nginx/html;
    location / {
        try_files $uri /index.html;
    }
    location /app1 {
        try_files $uri $uri/ /index.html;
    }
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name crewai.54.234.155.179.sslip.io;
    root /usr/share/nginx/html;
    location / {
        try_files $uri /index.html;
    }
    location /app2 {
        try_files $uri $uri/ /index.html;
    }
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}

server {
    listen 80;
    server_name lurobenceai.54.234.155.179.sslip.io;
    root /usr/share/nginx/html;
    location / {
        try_files $uri /index.html;
    }
    location /app3 {
        try_files $uri $uri/ /index.html;
    }
    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
