apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dynamic-ingress
  namespace: dev
  labels:
    app: dynamic-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: www.tecneuralai.com
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: dynamic-service
            port:
              number: 80
  - host: crewai.tecneuralai.com
    http:
      paths:
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: dynamic-service
            port:
              number: 80
  - host: lurobenceai.tecneuralai.com
    http:
      paths:
      - path: /app3
        pathType: Prefix
        backend:
          service:
            name: dynamic-service
            port:
              number: 80