# vpn — VPN certificate set for us-east-1
# 1 client cert: manovasanth
#
# Generated by DeepAgent. Reuse the emitted ARNs across multiple Client VPN
# endpoints. Regenerating any resource replaces just that piece; the CA is
# stable across replacements so existing client certs stay valid.

# ── Certificate Authority (self-signed, 10-year validity) ──
resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem = tls_private_key.ca.private_key_pem

  subject {
    common_name  = "vpn-ca"
    organization = "DeepAgent VPN Certificates"
  }

  is_ca_certificate     = true
  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "digital_signature",
  ]
}

# ── Server certificate (signed by the CA) ──
resource "tls_private_key" "server" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "server" {
  private_key_pem = tls_private_key.server.private_key_pem

  # AWS Client VPN rejects server certs without a DNS entry — CN in FQDN
  # form + DNS SAN so both validation paths pass.
  dns_names = ["vpn-server.deepagent.local"]

  subject {
    common_name  = "vpn-server.deepagent.local"
    organization = "DeepAgent VPN Certificates"
  }
}

resource "tls_locally_signed_cert" "server" {
  cert_request_pem   = tls_cert_request.server.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760 # 1 year — rotate before this expires

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "tls_private_key" "client_0" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "client_0" {
  private_key_pem = tls_private_key.client_0.private_key_pem

  subject {
    common_name  = "manovasanth"
    organization = "DeepAgent VPN Certificates"
  }
}

resource "tls_locally_signed_cert" "client_0" {
  cert_request_pem   = tls_cert_request.client_0.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "client_auth",
  ]
}

resource "aws_acm_certificate" "server" {
  private_key       = tls_private_key.server.private_key_pem
  certificate_body  = tls_locally_signed_cert.server.cert_pem
  certificate_chain = tls_self_signed_cert.ca.cert_pem
  tags              = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "vpn-certs-vpn"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-vpn-certificates-ui"
    "Purpose" = "vpn-server"
  }
}

resource "aws_acm_certificate" "client_ca" {
  private_key       = tls_private_key.ca.private_key_pem
  certificate_body  = tls_self_signed_cert.ca.cert_pem
  tags              = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "vpn-certs-vpn"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-vpn-certificates-ui"
    "Purpose" = "vpn-client-ca"
  }
}
