# agent-2-db — postgres 17.2 · db.t4g.micro
# Generated by DeepAgent. Rerunning the wizard regenerates this file.
# Look up the EKS cluster's VPC + private subnets + worker security group.
# Requires the cluster to already exist (built by the aks/eks flow).
data "aws_eks_cluster" "target" {
  name = "dev-cluster"
}

locals {
  eks_vpc_id           = data.aws_eks_cluster.target.vpc_config[0].vpc_id
  eks_subnet_ids       = data.aws_eks_cluster.target.vpc_config[0].subnet_ids
  eks_cluster_sg_id    = data.aws_eks_cluster.target.vpc_config[0].cluster_security_group_id
  # Workers use the "additional" SG when the cluster was built with one; fall
  # back to the cluster SG. Both are acceptable inbound sources for RDS.
  eks_worker_sg_ids    = concat(
    tolist(data.aws_eks_cluster.target.vpc_config[0].security_group_ids),
    [data.aws_eks_cluster.target.vpc_config[0].cluster_security_group_id],
  )
}

# Pick only the PRIVATE subnets (RDS should never sit in a public subnet).
data "aws_subnets" "private" {
  filter {
    name   = "vpc-id"
    values = [local.eks_vpc_id]
  }
  tags = { "kubernetes.io/role/internal-elb" = "1" }
}

resource "random_password" "db" {
  length           = 24
  special          = true
  # Exclude characters that require shell escaping when injected into env vars.
  override_special = "!#$%&*+-=?"
}

resource "aws_security_group" "rds" {
  name        = "agent-2-db-rds-sg"
  # AWS SG description charset is strict — ASCII-only, no em-dash / arrow / etc.
  # (regex ^[0-9A-Za-z_ .:/()#,@\[\]+=&;{}!$*-]*$). Keep this line ASCII.
  description = "RDS postgres for agent-2-db - inbound from EKS workers only"
  vpc_id      = local.eks_vpc_id
  tags        = {
    "ManagedBy" = "DeepAgent"
    "Database" = "agent-2-db"
    "Engine" = "postgres"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-rds"
  }
}

# Allow inbound Postgres/MySQL from EACH worker/cluster SG the EKS cluster uses.
# No 0.0.0.0/0 — the DB is only reachable from within the cluster's pods.
resource "aws_security_group_rule" "rds_ingress_from_eks" {
  count                    = length(local.eks_worker_sg_ids)
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  security_group_id        = aws_security_group.rds.id
  source_security_group_id = local.eks_worker_sg_ids[count.index]
  # AWS SG description charset is strict: ASCII only, and even the less-than
  # and greater-than characters are rejected (see aws_security_group.rds
  # above). No arrow-shaped strings like "->". Keep this line ASCII.
  description              = "EKS worker SG to RDS postgres on 5432"
}

resource "aws_security_group_rule" "rds_egress_all" {
  type              = "egress"
  from_port         = 0
  to_port           = 0
  protocol          = "-1"
  security_group_id = aws_security_group.rds.id
  cidr_blocks       = ["0.0.0.0/0"]
  description       = "RDS egress (DNS, package updates for maintenance)"
}

resource "aws_db_subnet_group" "rds" {
  name       = "agent-2-db-subnets"
  subnet_ids = data.aws_subnets.private.ids
  tags       = {
    "ManagedBy" = "DeepAgent"
    "Database" = "agent-2-db"
    "Engine" = "postgres"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-rds"
  }
}

resource "aws_db_instance" "rds" {
  identifier             = "agent-2-db"
  engine                 = "postgres"
  engine_version         = "17.2"
  instance_class         = "db.t4g.micro"
  allocated_storage      = 20
  max_allocated_storage  = 100
  storage_type           = "gp3"
  storage_encrypted      = true

  db_name                = "agent_2_db"
  username               = "app"
  # NOTE: this password lives in Terraform state. Keep the state backend
  # (S3 bucket) encrypted and least-privilege. For long-term production
  # migrate to IAM auth + IRSA (no static password).
  password               = random_password.db.result

  port                   = 5432
  db_subnet_group_name   = aws_db_subnet_group.rds.name
  vpc_security_group_ids = [aws_security_group.rds.id]
  publicly_accessible    = false

  backup_retention_period = 7
  backup_window           = "03:00-04:00"
  maintenance_window      = "sun:04:30-sun:05:30"
  auto_minor_version_upgrade = true
  copy_tags_to_snapshot   = true

  multi_az               = false
  deletion_protection    = true
  skip_final_snapshot    = false
  final_snapshot_identifier = "agent-2-db-final-${formatdate("YYYYMMDDhhmmss", timestamp())}"

  # Send Postgres logs to CloudWatch so the agent can query them via the
  # existing observability stack.
  enabled_cloudwatch_logs_exports = ["postgresql", "upgrade"]

  tags = {
    "ManagedBy" = "DeepAgent"
    "Database" = "agent-2-db"
    "Engine" = "postgres"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-rds"
  }
}