# client-vpn — AWS Client VPN in us-east-1
# 1 subnet association · certificate auth · full-tunnel · UDP/443 · certs: auto
# Generated by DeepAgent. Rerunning the wizard regenerates this file.

# ── Auto-generated PKI (CA + server + client) ──
# Terraform's tls provider generates keys + self-signed certs during apply,
# then aws_acm_certificate imports them into ACM in the Client VPN's region.
# Regenerate any of these and the endpoint picks up the new cert on next apply.

resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem = tls_private_key.ca.private_key_pem

  subject {
    common_name  = "client-vpn-ca"
    organization = "DeepAgent Client VPN"
  }

  is_ca_certificate     = true
  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "digital_signature",
  ]
}

resource "tls_private_key" "server" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "server" {
  private_key_pem = tls_private_key.server.private_key_pem

  # AWS Client VPN rejects server certs without a domain — CN must be a
  # FQDN-shape string AND we add a DNS SAN so both validation paths pass.
  dns_names = ["client-vpn-server.deepagent.local"]

  subject {
    common_name  = "client-vpn-server.deepagent.local"
    organization = "DeepAgent Client VPN"
  }
}

resource "tls_locally_signed_cert" "server" {
  cert_request_pem   = tls_cert_request.server.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760 # 1 year — rotate before this expires

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "tls_private_key" "client" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "client" {
  private_key_pem = tls_private_key.client.private_key_pem

  subject {
    common_name  = "client-vpn-client"
    organization = "DeepAgent Client VPN"
  }
}

resource "tls_locally_signed_cert" "client" {
  cert_request_pem   = tls_cert_request.client.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "client_auth",
  ]
}

resource "aws_acm_certificate" "server" {
  private_key       = tls_private_key.server.private_key_pem
  certificate_body  = tls_locally_signed_cert.server.cert_pem
  certificate_chain = tls_self_signed_cert.ca.cert_pem
  tags              = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "client-vpn"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-client-vpn-ui"
    "Purpose" = "client-vpn-server"
  }
}

resource "aws_acm_certificate" "client_ca" {
  private_key       = tls_private_key.ca.private_key_pem
  certificate_body  = tls_self_signed_cert.ca.cert_pem
  tags              = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "client-vpn"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-client-vpn-ui"
    "Purpose" = "client-vpn-client-ca"
  }
}

resource "aws_ec2_client_vpn_endpoint" "this" {
  description            = "client-vpn Client VPN"
  server_certificate_arn = aws_acm_certificate.server.arn
  client_cidr_block      = "10.100.0.0/22"
  vpc_id                 = "vpc-0458a23d9cb5dfece"
  split_tunnel           = false
  transport_protocol     = "udp"
  vpn_port               = 443
  session_timeout_hours  = 24

  authentication_options {
    type                       = "certificate-authentication"
    root_certificate_chain_arn = aws_acm_certificate.client_ca.arn
  }

  connection_log_options {
    enabled = false
  }

  tags = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "client-vpn"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-client-vpn-ui"
  }
}

resource "aws_ec2_client_vpn_network_association" "assoc_0" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.this.id
  subnet_id              = "subnet-0d1f45b13d2362e5e"
}

resource "aws_ec2_client_vpn_authorization_rule" "vpc" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.this.id
  target_network_cidr    = "10.0.0.0/16"
  authorize_all_groups   = true
  description            = "Allow reaching the target VPC"
}

resource "aws_ec2_client_vpn_authorization_rule" "internet" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.this.id
  target_network_cidr    = "0.0.0.0/0"
  authorize_all_groups   = true
  description            = "Allow internet-bound traffic (full-tunnel)"
}

resource "aws_ec2_client_vpn_route" "internet" {
  client_vpn_endpoint_id = aws_ec2_client_vpn_endpoint.this.id
  destination_cidr_block = "0.0.0.0/0"
  target_vpc_subnet_id   = "subnet-0d1f45b13d2362e5e"
  description            = "Full-tunnel internet route"

  depends_on = [aws_ec2_client_vpn_network_association.assoc_0]
}
