# jenkins — one-click Jenkins on EC2 (t3.small) in us-east-1
# Generated by DeepAgent. Rerunning the wizard regenerates this file.
#
# After apply completes, open the jenkins_url output in a browser, log in
# with the admin_username + the password you set, and rotate the password
# from Manage Jenkins → Users at your first login (the current password is
# visible in EC2 user-data metadata).

data "aws_ami" "amazon_linux" {
  most_recent = true
  owners      = ["amazon"]

  filter {
    name   = "name"
    values = ["al2023-ami-*-x86_64"]
  }
  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }
}

resource "aws_security_group" "this" {
  name        = "jenkins-jenkins-sg"
  description = "Jenkins UI + SSH ingress for jenkins"
  vpc_id      = "vpc-0458a23d9cb5dfece"

  ingress {
    description = "Jenkins UI"
    from_port   = 8080
    to_port     = 8080
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    description = "SSH"
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["223.185.25.28/32"]
  }

  egress {
    description = "Allow all outbound"
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "jenkins"
    "Component" = "jenkins"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-jenkins-ui"
  }
}

# SSM instance profile — lets you 'aws ssm start-session' into the box even
# if the SG blocks SSH. Zero extra cost, always useful.
resource "aws_iam_role" "this" {
  name = "jenkins-jenkins-role"
  assume_role_policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = { Service = "ec2.amazonaws.com" }
      Action = "sts:AssumeRole"
    }]
  })
  tags = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "jenkins"
    "Component" = "jenkins"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-jenkins-ui"
  }
}

resource "aws_iam_role_policy_attachment" "ssm" {
  role       = aws_iam_role.this.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
}

resource "aws_iam_instance_profile" "this" {
  name = "jenkins-jenkins-profile"
  role = aws_iam_role.this.name
}

resource "aws_instance" "this" {
  ami                         = data.aws_ami.amazon_linux.id
  instance_type               = "t3.small"
  subnet_id                   = "subnet-02782cd78b5c1ae81"
  vpc_security_group_ids      = [aws_security_group.this.id]
  associate_public_ip_address = true
  iam_instance_profile        = aws_iam_instance_profile.this.name
  key_name                    = "hari"

  root_block_device {
    volume_size = 30
    volume_type = "gp3"
    encrypted   = true
  }

  user_data                   = <<-USERDATA
    #!/bin/bash
    set -euo pipefail
    exec > >(tee /var/log/user-data.log|logger -t user-data) 2>&1
    
    echo "[+] Updating dnf + installing prerequisites"
    dnf update -y
    dnf install -y java-17-amazon-corretto-devel wget
    
    echo "[+] Adding Jenkins yum repo + installing"
    wget -qO /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
    rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io-2023.key
    dnf install -y jenkins
    
    echo "[+] Preparing Jenkins home + init.groovy.d admin bootstrap"
    mkdir -p /var/lib/jenkins/init.groovy.d
    cat > /var/lib/jenkins/init.groovy.d/00-create-admin.groovy <<'GROOVY'
    import jenkins.model.*
    import hudson.security.*
    
    def instance = Jenkins.getInstance()
    
    def hudsonRealm = new HudsonPrivateSecurityRealm(false)
    hudsonRealm.createAccount("admin", "admin123")
    instance.setSecurityRealm(hudsonRealm)
    
    def strategy = new FullControlOnceLoggedInAuthorizationStrategy()
    strategy.setAllowAnonymousRead(false)
    instance.setAuthorizationStrategy(strategy)
    
    // Skip the setup wizard state files (belt-and-braces vs the JAVA_OPTS flag).
    def state = new File("/var/lib/jenkins/jenkins.install.UpgradeWizard.state")
    state.parentFile.mkdirs()
    state.text = Jenkins.instance.version.toString()
    new File("/var/lib/jenkins/jenkins.install.InstallUtil.lastExecVersion").text = Jenkins.instance.version.toString()
    
    instance.save()
    println("[deepagent] Admin user 'admin' created + setup wizard skipped.")
    GROOVY
    
    chown -R jenkins:jenkins /var/lib/jenkins/init.groovy.d
    
    echo "[+] Configuring systemd override to skip the setup wizard"
    mkdir -p /etc/systemd/system/jenkins.service.d
    cat > /etc/systemd/system/jenkins.service.d/override.conf <<'OVERRIDE'
    [Service]
    Environment="JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Djava.awt.headless=true"
    OVERRIDE
    
    systemctl daemon-reload
    
    echo "[+] Enabling + starting Jenkins"
    systemctl enable jenkins
    systemctl start jenkins
    
    echo "[+] Waiting for Jenkins to accept HTTP on :8080 (up to 5 minutes)"
    for i in $$(seq 1 60); do
      if curl -fsS -o /dev/null http://localhost:8080/login; then
        echo "[+] Jenkins is up at http://localhost:8080"
        exit 0
      fi
      sleep 5
    done
    
    echo "[!] Jenkins did NOT come up within 5 min — check 'journalctl -u jenkins' and /var/log/user-data.log"
    exit 1
    
  USERDATA
  user_data_replace_on_change = true

  tags = merge({
    "ManagedBy" = "DeepAgent"
    "Stack" = "jenkins"
    "Component" = "jenkins"
    "Environment" = "dev"
    "CreatedBy" = "deepagent-jenkins-ui"
  }, { Name = "jenkins-jenkins" })
}
