# team-vpn — Azure OpenVPN endpoint in southcentralus
# split-tunnel · UDP/1194 · client CIDR 10.100.0.0/22
# Attaches to VNet vpn-aiagentvpc / subnet default in RG rg-devops.
# Generated by DeepAgent. Regenerating overwrites this file.

data "azurerm_resource_group" "this" {
  name = "rg-devops"
}

data "azurerm_virtual_network" "this" {
  name                = "vpn-aiagentvpc"
  resource_group_name = data.azurerm_resource_group.this.name
}

data "azurerm_subnet" "this" {
  name                 = "default"
  virtual_network_name = data.azurerm_virtual_network.this.name
  resource_group_name  = data.azurerm_resource_group.this.name
}

# ── Auto-generated PKI (CA + server + initial client cert) ──
# Same resource layout as gcp-openvpn.ts + client-vpn.ts so the shared
# resolveCaFromState helper works for all three providers. The CA private
# key is a SENSITIVE output — the app's issue-user endpoint uses it to mint
# additional per-user certs off this CA without re-running Terraform.

resource "tls_private_key" "ca" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_self_signed_cert" "ca" {
  private_key_pem = tls_private_key.ca.private_key_pem

  subject {
    common_name  = "vasanth-ca"
    organization = "DeepAgent Azure OpenVPN"
  }

  is_ca_certificate     = true
  validity_period_hours = 87600 # 10 years

  allowed_uses = [
    "cert_signing",
    "crl_signing",
    "digital_signature",
  ]
}

resource "tls_private_key" "server" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "server" {
  private_key_pem = tls_private_key.server.private_key_pem

  dns_names = ["vasanth-server.deepagent.local"]

  subject {
    common_name  = "vasanth-server.deepagent.local"
    organization = "DeepAgent Azure OpenVPN"
  }
}

resource "tls_locally_signed_cert" "server" {
  cert_request_pem   = tls_cert_request.server.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760 # 1 year — rotate before this expires

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "server_auth",
  ]
}

resource "tls_private_key" "client" {
  algorithm = "RSA"
  rsa_bits  = 2048
}

resource "tls_cert_request" "client" {
  private_key_pem = tls_private_key.client.private_key_pem

  subject {
    common_name  = "vasanth-client"
    organization = "DeepAgent Azure OpenVPN"
  }
}

resource "tls_locally_signed_cert" "client" {
  cert_request_pem   = tls_cert_request.client.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem

  validity_period_hours = 8760

  allowed_uses = [
    "key_encipherment",
    "digital_signature",
    "client_auth",
  ]
}

resource "azurerm_public_ip" "vpn" {
  name                = "team-vpn-openvpn-pip"
  location            = "southcentralus"
  resource_group_name = data.azurerm_resource_group.this.name
  allocation_method   = "Static"
  sku                 = "Standard"
  tags                = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "team-vpn"
    "Purpose" = "openvpn-endpoint"
    "Environment" = "prod"
    "CreatedBy" = "deepagent-azure-vpn-ui"
  }
}

resource "azurerm_network_security_group" "vpn" {
  name                = "team-vpn-openvpn-nsg"
  location            = "southcentralus"
  resource_group_name = data.azurerm_resource_group.this.name
  security_rule {
    name                       = "allow-openvpn-100"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Udp"
    source_port_range          = "*"
    destination_port_range     = "1194"
    source_address_prefix      = "0.0.0.0/0"
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "allow-ssh-from-vpn"
    priority                   = 110
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "10.100.0.0/22"
    destination_address_prefix = "*"
  }

  tags = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "team-vpn"
    "Purpose" = "openvpn-endpoint"
    "Environment" = "prod"
    "CreatedBy" = "deepagent-azure-vpn-ui"
  }
}

resource "azurerm_network_interface" "vpn" {
  name                = "team-vpn-openvpn-nic"
  location            = "southcentralus"
  resource_group_name = data.azurerm_resource_group.this.name

  # IP forwarding at the NIC layer — without this, Azure silently drops
  # packets whose source IP isn't the NIC's own IP. Breaks NAT'd tunnel
  # traffic. Required for any router / NAT / VPN VM.
  ip_forwarding_enabled = true

  ip_configuration {
    name                          = "primary"
    subnet_id                     = data.azurerm_subnet.this.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id          = azurerm_public_ip.vpn.id
  }

  tags = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "team-vpn"
    "Purpose" = "openvpn-endpoint"
    "Environment" = "prod"
    "CreatedBy" = "deepagent-azure-vpn-ui"
  }
}

resource "azurerm_network_interface_security_group_association" "vpn" {
  network_interface_id      = azurerm_network_interface.vpn.id
  network_security_group_id = azurerm_network_security_group.vpn.id
}

# custom_data is cloud-init's UserData. We assemble the PEMs from Terraform
# state into the script inline, then base64-encode the whole thing (Azure
# expects custom_data to be pre-encoded).
locals {
  vpn_startup_script = replace(
    replace(
      replace(
        <<-STARTUP
        #!/bin/bash
        set -euo pipefail
        exec > /var/log/deepagent-openvpn-startup.log 2>&1
        echo "[deepagent] OpenVPN startup: $(date -u)"
        
        if [[ -f /etc/openvpn/.provisioned ]]; then
          echo "[deepagent] Already provisioned — skipping."
          exit 0
        fi
        
        export DEBIAN_FRONTEND=noninteractive
        apt-get update -y
        apt-get install -y openvpn iptables-persistent openssl
        
        # ── PEMs are embedded below by Terraform (base64 encoded) ──
        mkdir -p /etc/openvpn/server /etc/openvpn/ccd
        cat > /etc/openvpn/server/ca.crt     <<'CAEOF'
        __CA_CERT_PEM_PLACEHOLDER__
        CAEOF
        cat > /etc/openvpn/server/server.crt <<'SRVCERTEOF'
        __SERVER_CERT_PEM_PLACEHOLDER__
        SRVCERTEOF
        cat > /etc/openvpn/server/server.key <<'SRVKEYEOF'
        __SERVER_KEY_PEM_PLACEHOLDER__
        SRVKEYEOF
        chmod 600 /etc/openvpn/server/server.key
        
        # ── DH params (2048-bit; ~30-60s on Standard_B1s) ──
        openssl dhparam -out /etc/openvpn/server/dh.pem 2048
        
        # ── Server config ──
        cat > /etc/openvpn/server/server.conf <<'OVPNEOF'
        port 1194
        proto udp
        dev tun
        ca   /etc/openvpn/server/ca.crt
        cert /etc/openvpn/server/server.crt
        key  /etc/openvpn/server/server.key
        dh   /etc/openvpn/server/dh.pem
        topology subnet
        server 10.100.0.0 255.255.252.0
        ifconfig-pool-persist /var/log/openvpn/ipp.txt
        # Split-tunnel: only advertise the VNet route to clients.
        push "route 10.0.0.0 255.255.255.0"
        keepalive 10 60
        cipher AES-256-GCM
        data-ciphers AES-256-GCM:AES-128-GCM
        auth SHA256
        persist-key
        persist-tun
        user  nobody
        group nogroup
        verb 3
        status /var/log/openvpn/status.log
        log-append /var/log/openvpn/openvpn.log
        OVPNEOF
        mkdir -p /var/log/openvpn
        
        # ── IP forwarding + iptables NAT ──
        sysctl -w net.ipv4.ip_forward=1
        grep -q "^net.ipv4.ip_forward" /etc/sysctl.conf && \
          sed -i 's/^net.ipv4.ip_forward.*/net.ipv4.ip_forward=1/' /etc/sysctl.conf || \
          echo "net.ipv4.ip_forward=1" >> /etc/sysctl.conf
        
        IFACE=$(ip route show default | awk '/default/ {print $5; exit}')
        iptables -t nat -A POSTROUTING -s 10.100.0.0/22 -o "$IFACE" -j MASQUERADE
        iptables -A FORWARD -i tun+ -o "$IFACE" -j ACCEPT
        iptables -A FORWARD -i "$IFACE" -o tun+ -j ACCEPT
        netfilter-persistent save
        
        # ── Enable + start ──
        systemctl enable openvpn-server@server
        systemctl start  openvpn-server@server
        
        touch /etc/openvpn/.provisioned
        echo "[deepagent] OpenVPN startup: DONE $(date -u)"
        
        STARTUP
        ,
        "__CA_CERT_PEM_PLACEHOLDER__",
        chomp(tls_self_signed_cert.ca.cert_pem)
      ),
      "__SERVER_CERT_PEM_PLACEHOLDER__",
      chomp(tls_locally_signed_cert.server.cert_pem)
    ),
    "__SERVER_KEY_PEM_PLACEHOLDER__",
    chomp(tls_private_key.server.private_key_pem)
  )
}

resource "azurerm_linux_virtual_machine" "vpn" {
  name                  = "team-vpn-openvpn"
  location              = "southcentralus"
  resource_group_name   = data.azurerm_resource_group.this.name
  size                  = "Standard_D2s_v3"
  admin_username        = "azureuser"
  network_interface_ids = [azurerm_network_interface.vpn.id]

  admin_ssh_key {
    username   = "azureuser"
    public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCKU7XtDLek3DDW64SWBg6o4oF3mtnf91pr6TX1xsnAwVcfxKwvPCGROceTAHGT7xT79SLfSrDnKJZxaxf1Yadq7Ab9+qGMwdOqGeWhFWyzizdmBXY6eQrFhIAL+Ylem5c38Eva1aXOINMfKTZkuqL9HiUUBB+bBzdJML6oNWUOAmoN7srWPZD5sMXH0Yvx5Q2wEHX4/WzVr2Zb/Hd/hYQ2JC1Z+lpM8OdqugZ0GrMF5J/vRIg9RckZ2m8GZpP7YgQr5Aw40l+3gMfaML9ywc1ojIuqwGz29c9SERi6w0SA+C1BELY13fgLoj6JtxyK+s60w4sYbV27W/Ys7ZHxu9ov team-vpn-azure-vpn-admin"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = 30
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "0001-com-ubuntu-server-jammy"
    sku       = "22_04-lts-gen2"
    version   = "latest"
  }

  custom_data = base64encode(local.vpn_startup_script)

  tags = {
    "ManagedBy" = "DeepAgent"
    "Stack" = "team-vpn"
    "Purpose" = "openvpn-endpoint"
    "Environment" = "prod"
    "CreatedBy" = "deepagent-azure-vpn-ui"
  }
}
